### ISSUE TITLE
Reset Quests when starting new game

### ISSUE THREAD

**Issue by ralf1991** [TheWalruzz/godot-questify#10]
I have a problem resetting the quests. Due to my lack of Godot experience, I can't solve the problem even after several hours.
I have the following scenario: The player starts a new game and completes the first quest. He then switches back to the main menu and starts a new game again. If he now wants to start the first quest a second time, it is automatically completed.
I suspect the error (if it's not just me) in the quest_resource.gd -> line 33. The QuestResource is loaded as a fresh copy using duplicate(true). However, according to the documentation and tests, the duplicate function cannot handle resource arrays. So although the QuestResource itself is freshly loaded, its nodes are still the old, already completed ones.
Can you confirm an error here or is it just me?

Thank you very much for your work! I can't wait to use your asset in my game.

![image](https://github.com/user-attachments/assets/e9ccf8b3-fd67-41df-b782-233efcb9c75c)
![image](https://github.com/user-attachments/assets/52fabaf4-5549-49e2-94b9-51d039e8a674)

Edit: I‘m using Godot 4.3

**Comment by TheWalruzz** [comment]
Hmm, it seemed to work before 4.3. I'm away from my computer atm, but will investigate it tomorrow

**Comment by TheWalruzz** [comment]
Ok, this should be fixed now. You were right - arrays in resources cannot be duplicated, so I had to manually duplicate each node and edge, but this seems to do the trick.

Let me know if you have any other problems or ideas for improvement

**Comment by ralf1991** [comment]
Awesome! Now everything works as expected. Saving, loading, resetting - I was able to try everything out successfully! 😊
Thank you so much for looking at this so quickly!
