### ISSUE TITLE
Nonexistent function 'get_previous_nodes' in base 'Nil'

### ISSUE THREAD

**Issue by ralf1991** [TheWalruzz/godot-questify#11]
Hey! I'm sorry to have to disturb you again. But after I've added a few quests to my game today and everything looked good at first, I noticed a new bug at the end.

The error occurs after repeated serialization and deserialization:

1. var data : Array = Questify.serialize()
2. Questify.deserialize(data)
3. data = Questify.serialize() <--- Error accessing “_graph”

This problem did not exist before your last fix.
I've added a demonstration of the bug to the test scene here: 
https://github.com/TheWalruzz/godot-questify/compare/main...ralf1991:godot-questify:serialize-error-demonstration

If I'm able to solve the problem myself, I will create a pull request. But at the moment I'm still going round in circles.

**Comment by TheWalruzz** [comment]
From my initial investigation, it has to do with how the data is deserialized. Nodes are not initialized properly after that, so serialization fails. I'll try to figure this one shortly

**Comment by TheWalruzz** [comment]
Fix is pushed, it should work again
