### ISSUE TITLE
Impossible to delete nodes

### ISSUE THREAD

**Issue by Nordsoft91** [TheWalruzz/godot-questify#2]
There is no button to remove node neither on toolbar nor in context menu. Delete hotkey also doesn't work

<img width="701" alt="Снимок экрана 2024-05-27 в 23 10 19" src="https://github.com/TheWalruzz/godot-questify/assets/9308612/b7d66533-a039-4559-8e9b-438250b853d3">

Same problem with connections.

**Comment by TheWalruzz** [comment]
That's weird, last time I checked, Delete button worked fine. I'll see if I can reproduce this issue later

**Comment by Nordsoft91** [comment]
Cut, copy, paste, undo, redo don't work too. Note, that it could be platform specific, I use mac.

**Comment by TheWalruzz** [comment]
Hmm, that could be it. I'll see if there's an easy fix

**Comment by TheWalruzz** [comment]
Weird, it works fine on Windows and Linux and it uses native event handlers for GraphEdit node, so it should all be handled by Godot out of the box

**Comment by Nordsoft91** [comment]
I made recording where I use delete - it deletes node from my scene instead. Maybe godot bug, but still significantly restricts usage.

https://github.com/TheWalruzz/godot-questify/assets/9308612/a2d9c5d9-68a9-4f1a-ae1b-25461f98b023

**Comment by TheWalruzz** [comment]
Hmmm, it looks like it's somehow not registering that node is selected, interesting. I'll do some more research into that

**Comment by TheWalruzz** [comment]
I still have no clue what's going on here and without a Mac it's impossible for me to debug. Could you please try using a debugger on https://github.com/TheWalruzz/godot-questify/blob/main/addons/questify/scripts/quest_graph_editor.gd#L177 to see if it actually emits `node_selected` signal in your case? Also, on which version of Godot are you?

**Comment by Nordsoft91** [comment]
Node selection works, but delete signal is not sent. I used visual shader nodes to test it and it has same issue.
Reported to Godot official https://github.com/godotengine/godot/issues/92776

**Comment by TheWalruzz** [comment]
Thanks for checking it! This issue can be closed now,
