### ISSUE TITLE
quest_completed is not emitted

### ISSUE THREAD

**Issue by Nordsoft91** [TheWalruzz/godot-questify#3]
If quest doesn't have objectives, quest is not completed. Minor, but still inconsistent behavior.

<img width="530" alt="Снимок экрана 2024-05-28 в 01 15 26" src="https://github.com/TheWalruzz/godot-questify/assets/9308612/2d4d70bc-cae2-4206-a578-9bf598c9e82c">

**Comment by TheWalruzz** [comment]
That's an edge case that will never happen in reality, since quests should have at least one objective. I can add a warning or something that will inform the user that this quest resource is invalid.

**Comment by Nordsoft91** [comment]
Warning would be good, because this scene was first what I tried after installing addon. So I was thinking that quest completion must be implemented in game code manually

**Comment by TheWalruzz** [comment]
I've added a simple `printerr` when trying to save and no objectives are added. I'm planning to do a major error/warning handling refactor in the future, but this should be enough for now.
