### ISSUE TITLE
4.3 save dialogue

### ISSUE THREAD

**Issue by SlashScreen** [TheWalruzz/godot-questify#8]
In 4.3 rc2, the save file dialogue appears every time you hit save, even if the questify tab isn't open, or anything has been changed.

**Comment by TheWalruzz** [comment]
I'll be doing a general upgrade when 4.3 goes live, so it'll be fixed then. Thanks for letting me know!

**Comment by SlashScreen** [comment]
In the meantime, here's a workaround for those also annoyed by this problem.
in `addons/questify/scripts/quest_editor_view.gd:60` change the `save_changes()` method to the following:
```
func save_changes() -> void:
	if current_file_path.is_empty():
		if quest_graph_editor.find_children("", "QuestGraphNode", false, false).is_empty():
			return
		save_file_dialog.popup()
	else:
		save_file(current_file_path)
```

**Comment by TheWalruzz** [comment]
Version 1.3.2 with above fix is now live, good luck with your project! 😄

**Comment by SlashScreen** [comment]
Could I ask you to credit me for this, since I came up with the fix?
